import { IUserRepo } from 'database/repository.interfaces/user.repo.intrerface';
import { UserDomainModel } from 'domain.types/user/user.domain.model';
import { UserDetailsDto } from 'domain.types/user/user.dto';
import { inject, injectable } from 'tsyringe';

@injectable()
export class UserService {

    constructor(
        @inject('IUserRepo') private _userRepo: IUserRepo,
    ) {}

    create = async (userDetails: UserDomainModel): Promise<UserDetailsDto> => {

        const autoGeneratedUsername = userDetails.FirstName + "_0981" + userDetails.LastName;
        const userDetailsDto: UserDetailsDto = await this._userRepo.createUser(userDetails)
        userDetails.UserName = autoGeneratedUsername;
        
        return userDetailsDto
    };
}
